language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - py.test
  - nosetests --with-coverage --cover-tests --cover-package=tests
after_success:
  - coveralls
  - pytest   
